parameters:
#    sdz_blog.example.class: Sdz\Blog\Bundle\Example

services:
#    sdz_blog.example:
#        class: %sdz_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    sdzblog.validator.antiflood:								 # Le nom du service
        class : Sdz\Blog\Bundle\Validator\AntifloodValidator	 
        arguments : [@request, @doctrine.orm.entity_manager]	 
        scope : request                                         
        tags :
             - { name: validator.constraint_validator, alias: sdzblog_antiflood }  
#    sdz_blog.antispam:
#       class : Sdz\Blog\Bundle\Antispam\SdzAntispam
#       arguments : [@mailer, %locale%, 3]